# Generated by Django 3.0.8 on 2020-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='categories',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
