# Generated by Django 3.0.8 on 2020-07-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200726_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='watchlist',
            new_name='users_watchlist',
        ),
    ]
